### ISSUE TITLE
Possible memory build up

### ISSUE THREAD

**Issue by tugcanolgun** [henvo/golang-gin-gorm-starter#1]
DISCLAIMER: I am fairly new to go, so I may be missing something here.

As pointed in [this gorm issue](https://github.com/go-gorm/gorm/issues/3677), if you don't close the connection to the database, a new goroutine is created everytime you query the database. I have seen this via [the comment](http://disq.us/p/2cqnyuq) on gorm's website of the same person who started given issue. 

Using [statsviz](https://github.com/arl/statsviz), I tested it myself (not through this repo) and goroutines created are staying there until the program is terminated. 

You may want to check [this usage on gorm's website](https://gorm.io/docs/generic_interface.html) and opt to close the connection after use.

**Comment by henvo** [comment]
Hey @tugcanolgun 

Thank you very much for your input!
I tried to understand the issue and reproduce it. So I did the following:

**Setup**:
* Printed `runtime.NumGoroutines())` after every API call.
* Checked the number of open connections with `SHOW status WHERE variable_name = 'threads_connected';`.

**Result**:
No matter how many requests I perform - the numbers (goroutines, connected threads) stay the same.

Let me know if I missed something else but I can't reproduce/confirm this issue.
